global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # The metrics endpoint
    static_configs:
      - targets: ['localhost:8080']  # Update this with your application host and port

rule_files:
  - "alert.rules"  # Reference to your alert rules file
